    - name: Ensure flask is installed
      pip:
        name: ['flask', 'flask-mysql']
        state: present

    - name: Copy the Python Application
      copy: src=../../../../app.py dest=/opt/app.py

    - name: Start the Python Application
      shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &
